/**
 * Curated signatures and one-line descriptions for the functions people
 * reach for most. HyperFormula exposes the full registered name list (400+)
 * but not parameter names, so this table is what makes the autocomplete
 * list and the argument hint readable; any other registered function is
 * still offered by name with a generic `(…)`.
 */
export interface FunctionSignature {
  /** Parameter list as shown to the user, e.g. `number1, [number2], …`. */
  params: string;
  description: string;
}

export const FUNCTION_SIGNATURES: Record<string, FunctionSignature> = {
  SUM: { params: 'number1, [number2], …', description: 'Adds up numbers or ranges.' },
  AVERAGE: { params: 'number1, [number2], …', description: 'Average of the numbers.' },
  MIN: { params: 'number1, [number2], …', description: 'Smallest number.' },
  MAX: { params: 'number1, [number2], …', description: 'Largest number.' },
  COUNT: { params: 'value1, [value2], …', description: 'How many cells contain numbers.' },
  COUNTA: { params: 'value1, [value2], …', description: 'How many cells are not empty.' },
  COUNTBLANK: { params: 'range', description: 'How many cells are empty.' },
  COUNTIF: { params: 'range, criterion', description: 'Counts cells that meet a condition, e.g. ">10".' },
  COUNTIFS: { params: 'range1, criterion1, [range2, criterion2], …', description: 'Counts cells that meet every condition.' },
  SUMIF: { params: 'range, criterion, [sum_range]', description: 'Adds the cells that meet a condition.' },
  SUMIFS: { params: 'sum_range, range1, criterion1, …', description: 'Adds cells that meet every condition.' },
  AVERAGEIF: { params: 'range, criterion, [average_range]', description: 'Average of cells that meet a condition.' },
  SUMPRODUCT: { params: 'range1, [range2], …', description: 'Multiplies matching cells, then adds the products.' },
  PRODUCT: { params: 'number1, [number2], …', description: 'Multiplies the numbers.' },
  MEDIAN: { params: 'number1, [number2], …', description: 'Middle value.' },
  STDEV: { params: 'number1, [number2], …', description: 'Standard deviation of a sample.' },
  VAR: { params: 'number1, [number2], …', description: 'Variance of a sample.' },
  ROUND: { params: 'number, [places]', description: 'Rounds to a number of decimal places.' },
  ROUNDUP: { params: 'number, [places]', description: 'Rounds away from zero.' },
  ROUNDDOWN: { params: 'number, [places]', description: 'Rounds toward zero.' },
  INT: { params: 'number', description: 'Rounds down to a whole number.' },
  ABS: { params: 'number', description: 'Absolute value.' },
  SQRT: { params: 'number', description: 'Square root.' },
  POWER: { params: 'base, exponent', description: 'Raises a number to a power.' },
  MOD: { params: 'number, divisor', description: 'Remainder after division.' },
  RAND: { params: '', description: 'Random number between 0 and 1.' },
  RANDBETWEEN: { params: 'low, high', description: 'Random whole number in a range.' },
  IF: { params: 'condition, value_if_true, [value_if_false]', description: 'Returns one value if a condition is true, another if false.' },
  IFS: { params: 'condition1, value1, [condition2, value2], …', description: 'Returns the value for the first true condition.' },
  IFERROR: { params: 'value, value_if_error', description: 'Replaces an error with another value.' },
  AND: { params: 'condition1, [condition2], …', description: 'TRUE if every condition is true.' },
  OR: { params: 'condition1, [condition2], …', description: 'TRUE if any condition is true.' },
  NOT: { params: 'condition', description: 'Flips TRUE and FALSE.' },
  TRUE: { params: '', description: 'The value TRUE.' },
  FALSE: { params: '', description: 'The value FALSE.' },
  ISBLANK: { params: 'value', description: 'TRUE if the cell is empty.' },
  ISNUMBER: { params: 'value', description: 'TRUE if the value is a number.' },
  ISTEXT: { params: 'value', description: 'TRUE if the value is text.' },
  ISERROR: { params: 'value', description: 'TRUE if the value is an error.' },
  CHOOSE: { params: 'index, value1, [value2], …', description: 'Picks a value by position.' },
  VLOOKUP: { params: 'search_key, range, column_index, [is_sorted]', description: 'Looks down the first column of a range and returns a value from the same row.' },
  HLOOKUP: { params: 'search_key, range, row_index, [is_sorted]', description: 'Looks across the first row of a range and returns a value from the same column.' },
  XLOOKUP: { params: 'search_key, lookup_range, return_range, [if_not_found]', description: 'Finds a value in one range and returns the matching value from another.' },
  INDEX: { params: 'range, row, [column]', description: 'Returns the cell at a row and column of a range.' },
  MATCH: { params: 'search_key, range, [match_type]', description: 'Position of a value in a range.' },
  FILTER: { params: 'range, condition1, [condition2], …', description: 'Rows of a range that meet the conditions.' },
  UNIQUE: { params: 'range', description: 'Distinct rows of a range.' },
  SORT: { params: 'range, [sort_column], [is_ascending]', description: 'Sorts the rows of a range.' },
  SEQUENCE: { params: 'rows, [columns], [start], [step]', description: 'A grid of sequential numbers.' },
  TRANSPOSE: { params: 'range', description: 'Swaps rows and columns.' },
  TODAY: { params: '', description: "Today's date." },
  NOW: { params: '', description: 'The current date and time.' },
  DATE: { params: 'year, month, day', description: 'Builds a date.' },
  DAY: { params: 'date', description: 'Day of the month.' },
  MONTH: { params: 'date', description: 'Month number.' },
  YEAR: { params: 'date', description: 'Year.' },
  WEEKDAY: { params: 'date, [type]', description: 'Day of the week as a number.' },
  EOMONTH: { params: 'start_date, months', description: 'Last day of the month, some months away.' },
  EDATE: { params: 'start_date, months', description: 'The same day, some months away.' },
  DATEDIF: { params: 'start_date, end_date, unit', description: 'Days, months or years between two dates ("D", "M", "Y").' },
  NETWORKDAYS: { params: 'start_date, end_date, [holidays]', description: 'Working days between two dates.' },
  DAYS: { params: 'end_date, start_date', description: 'Days between two dates.' },
  TEXT: { params: 'value, format', description: 'Formats a number as text, e.g. TEXT(A1, "0.00").' },
  LEN: { params: 'text', description: 'Number of characters.' },
  LEFT: { params: 'text, [count]', description: 'Characters from the start.' },
  RIGHT: { params: 'text, [count]', description: 'Characters from the end.' },
  MID: { params: 'text, start, count', description: 'Characters from the middle.' },
  CONCATENATE: { params: 'text1, [text2], …', description: 'Joins text together.' },
  TEXTJOIN: { params: 'separator, ignore_empty, text1, [text2], …', description: 'Joins text with a separator.' },
  TRIM: { params: 'text', description: 'Removes extra spaces.' },
  UPPER: { params: 'text', description: 'UPPERCASE.' },
  LOWER: { params: 'text', description: 'lowercase.' },
  PROPER: { params: 'text', description: 'Capitalizes Each Word.' },
  SUBSTITUTE: { params: 'text, search_for, replace_with, [occurrence]', description: 'Replaces text.' },
  FIND: { params: 'search_for, text, [start]', description: 'Position of text (case-sensitive).' },
  SEARCH: { params: 'search_for, text, [start]', description: 'Position of text (not case-sensitive).' },
  SPLIT: { params: 'text, delimiter', description: 'Splits text into cells.' },
  VALUE: { params: 'text', description: 'Converts text to a number.' },
  PMT: { params: 'rate, periods, present_value, [future_value], [type]', description: 'Loan payment per period.' },
  FV: { params: 'rate, periods, payment, [present_value], [type]', description: 'Future value of an investment.' },
  PV: { params: 'rate, periods, payment, [future_value], [type]', description: 'Present value of an investment.' },
  NPV: { params: 'rate, cashflow1, [cashflow2], …', description: 'Net present value.' },
  IRR: { params: 'cashflows, [guess]', description: 'Internal rate of return.' },
  FINANCE: { params: '"base", "quote"', description: 'Exchange rate from one currency to another, e.g. FINANCE("USD","EUR").' },
};

/** Functions listed first in autocomplete when several match — the ones people mean most often. */
export const POPULAR_FUNCTIONS = [
  'SUM',
  'AVERAGE',
  'COUNT',
  'IF',
  'MIN',
  'MAX',
  'VLOOKUP',
  'ROUND',
  'TODAY',
  'FINANCE',
];
